### ISSUE TITLE
Should not build documentation by default.

### ISSUE THREAD

**Issue by sirherrbatka** [memsharded/conan-zmq#8]
https://github.com/memsharded/conan-zmq/blob/2aab3449d3a0e4dcd9b3b59b54ab0949ee502d68/conanfile.py#L29
just add -DWITH_DOC=OFF

**Comment by memsharded** [comment]
Yes, that would be better. Fixed in https://github.com/memsharded/conan-zmq/commit/8b13288a403ac6c84454cc8b84d5c9c943ba8e38

Thanks for telling, this one was easy, next time feel free to submit a PR :)

**Comment by sirherrbatka** [comment]
Thanks for fixing this issue. I could not find button for creating inlined merge request (I was told that this is a thing) to be honest ;-)
